config/routes.rb
Rails.application.routes.draw do
  
  resources :searches
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :items
  resources :relationships, only: [:create, :destroy]
  
  root    'items#index'

  get     'cart/index'
  
  get     'about' => 'static_pages#about'
  get     'contact' => 'static_pages#contact'
  get     '/help',            to: 'static_pages#help'
  
  resources :items
  get 'password_resets/new'

  get 'password_resets/edit'
  
  get 'category/:title', to: 'static_pages#category'

  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  post    '/register',        to: 'users#create'
  get     '/register',        to: 'users#register'
  
  get     '/cart',            to:  'cart#index'
  get     '/cart/clear',      to:  'cart#clearCart'
  get     '/cart/:id(.:format)',        to:  'cart#add'
  get     '/cart/:image_url', to:  'cart#image_url'
  
  get     '/cart/remove/:id', to:   'cart#remove'
  
  delete  'logout',          to:   'sessions#destroy'
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   HRM - Horse Racing Merchandise, Arkle House, Sea The Stars Road, Denman, Dublin 15
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '/about' %></li>
      <li><%= link_to "Contact", '/contact' %></li>
      <li><%= link_to "Help", '/help' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav>
        <%= link_to image_tag("Logo.png", alt: "HRM logo"),
          '/' %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   '/' %></li>
          <li><%= link_to "Cart",   '/cart' %></li>
          <li><%= link_to "Search", new_search_path %></li>
        
          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
            <% if @admin_user = false %>
              <li><%= link_to "Order", current_user %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
            <% end %>
        </ul>
          </li>
        <% else %>
          <li><%= link_to "Register", '/register' %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_ie9.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/ie9' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>